<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>{{groupId}}</groupId>
    <artifactId>{{artifactId}}</artifactId>
    <version>{{version}}</version>
  </parent>
  <artifactId>{{artifactId}}.ui.apps</artifactId>
  <version>{{version}}</version>
  <packaging>content-package</packaging>
  <name>{{appTitle}} - UI apps</name>
  <description>UI apps package for {{appTitle}}</description>
  <dependencies>
    <dependency>
      <groupId>{{groupId}}</groupId>
      <artifactId>{{artifactId}}.ui.apps.structure</artifactId>
      <version>{{version}}</version>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>com.adobe.aem</groupId>
      <artifactId>aem-sdk-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.scripting.sightly.runtime</artifactId>
      <version>1.2.4-1.4.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src/main/content/jcr_root</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.jackrabbit</groupId>
        <artifactId>filevault-package-maven-plugin</artifactId>
        <configuration>
          <properties>
            <cloudManagerTarget>none</cloudManagerTarget>
          </properties>
          <group>{{groupId}}</group>
          <name>{{artifactId}}.ui.apps</name>
          <packageType>application</packageType>
          <repositoryStructurePackages>
            <repositoryStructurePackage>
              <groupId>{{groupId}}</groupId>
              <artifactId>{{artifactId}}.ui.apps.structure</artifactId>
            </repositoryStructurePackage>
          </repositoryStructurePackages>
          <dependencies></dependencies>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.day.jcr.vault</groupId>
        <artifactId>content-package-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <verbose>true</verbose>
          <failOnError>true</failOnError>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.sling</groupId>
        <artifactId>htl-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>validate-htl-scripts</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <generateJavaClasses>true</generateJavaClasses>
              <generatedJavaClassesPrefix>org.apache.sling.scripting.sightly</generatedJavaClassesPrefix>
              <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
              <allowedExpressionOptions>
                <allowedExpressionOption>cssClassName</allowedExpressionOption>
                <allowedExpressionOption>decoration</allowedExpressionOption>
                <allowedExpressionOption>decorationTagName</allowedExpressionOption>
                <allowedExpressionOption>wcmmode</allowedExpressionOption>
              </allowedExpressionOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
