const GENERATED_PREFIX = '// Generated by api-integrations api-codegen from contract ';
const SUPPORTED_CLIENT_DEPS = new Set(['recaptcha', 'recaptcha-enterprise', 'cookie', 'title', 'location', 'constant']);
const RESERVED_WORDS = new Set([
  'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete',
  'do', 'else', 'enum', 'export', 'extends', 'finally', 'for', 'function', 'if', 'import', 'in',
  'instanceof', 'let', 'new', 'return', 'super', 'switch', 'this', 'throw', 'try', 'typeof', 'var',
  'void', 'while', 'with', 'yield',
]);

function singleQuoted(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n')}'`;
}

function safeString(value) {
  return JSON.stringify(String(value))
    .replace(/</g, '\\u003c')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function jsLiteral(value, indent = 0) {
  const base = ' '.repeat(indent);
  const child = ' '.repeat(indent + 2);
  if (Array.isArray(value)) {
    if (!value.length) return '[]';
    const entries = value.map((entry) => `${child}${jsLiteral(entry, indent + 2)}`);
    return `[\n${entries.join(',\n')}\n${base}]`;
  }
  if (isPlainObject(value)) {
    const entries = Object.entries(value);
    if (!entries.length) return '{}';
    const lines = entries.map(([key, entry]) => `${child}${safeString(key)}: ${jsLiteral(entry, indent + 2)}`);
    return `{\n${lines.join(',\n')}\n${base}}`;
  }
  if (typeof value === 'string') return safeString(value);
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'boolean') return String(value);
  return 'null';
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function placeholder(value) {
  return typeof value === 'string'
    && /^<(?:email|phone|token|recaptcha|redacted|test:[\w-]+|cookie:[\w-]+)>$/i.test(value);
}

function pathParts(path) {
  return String(path || '').replace(/\[(\d+)\]/g, '.$1').split('.').filter(Boolean);
}

function setPath(target, path, value) {
  const parts = pathParts(path);
  if (!parts.length) return target;
  let current = target;
  parts.slice(0, -1).forEach((part, index) => {
    if (!isPlainObject(current[part]) && !Array.isArray(current[part])) {
      current[part] = /^\d+$/.test(parts[index + 1]) ? [] : {};
    }
    current = current[part];
  });
  current[parts.at(-1)] = value;
  return target;
}

function skeletonFromSchema(schema = {}) {
  if (schema.type === 'array') return [];
  if (schema.type === 'object') {
    return Object.fromEntries(Object.keys(schema.properties || {}).map((key) => [key, skeletonFromSchema(schema.properties[key])]));
  }
  if (schema.type === 'boolean') return false;
  if (schema.type === 'number' || schema.type === 'integer') return 0;
  return '';
}

function sanitizedTemplate(value) {
  if (Array.isArray(value)) return value.map(sanitizedTemplate);
  if (isPlainObject(value)) return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, sanitizedTemplate(child)]));
  if (placeholder(value)) return '';
  return value ?? '';
}

function requestTemplate(contract) {
  const template = contract.requestExample !== null && contract.requestExample !== undefined
    ? sanitizedTemplate(contract.requestExample)
    : skeletonFromSchema(contract.requestSchema || {});
  (contract.fieldMap || []).forEach((entry) => setPath(template, entry.path, ''));
  (contract.clientDeps || []).filter((dep) => dep.from !== 'constant').forEach((dep) => setPath(template, dep.path, ''));
  return template;
}

function multipartFields(contract, contentType) {
  if (contentType !== 'multipart/form-data' || !Array.isArray(contract.requestExample?.fields)) return [];
  return contract.requestExample.fields.map((name) => {
    const match = (contract.fieldMap || []).find((entry) => entry.name === name || entry.path === name);
    return { name, path: match?.path || name };
  });
}

function queryKeys(contract) {
  const explicit = contract.queryKeys || contract.requiredQueryKeys || contract.requestQueryKeys;
  if (Array.isArray(explicit)) return [...new Set(explicit.map(String).filter(Boolean))].sort();
  try {
    const parsed = new URL(contract.endpoint);
    return [...new Set([...parsed.searchParams.keys()])].sort();
  } catch {
    return [];
  }
}

function headerValue(contract, name) {
  const lower = String(name).toLowerCase();
  return contract.headers?.[lower] || contract.headers?.[name] || contract.requestHeaders?.[lower] || contract.requestHeaders?.[name] || null;
}

function acceptHeader(contract) {
  return contract.accept || contract.acceptHeader || headerValue(contract, 'accept');
}

function graphqlQuery(contract) {
  return contract.graphql?.query
    || contract.graphql?.document
    || contract.graphql?.queryDocument
    || contract.requestExample?.query
    || null;
}

function graphqlPersistedHash(contract) {
  return contract.graphql?.persistedHash || contract.graphql?.sha256Hash || null;
}

export function generatedMarker(id) {
  return `${GENERATED_PREFIX}${id}. Edits are overwritten on re-run.`;
}

export function hasGeneratedMarker(source) {
  return String(source || '').split(/\r?\n/, 1)[0].startsWith(GENERATED_PREFIX);
}

export function camelAlias(id) {
  const base = String(id || '').split(/[^0-9A-Za-z]+/).filter(Boolean).map((part, index) => {
    const lower = part.charAt(0).toLowerCase() + part.slice(1);
    if (index === 0) return lower;
    return lower.charAt(0).toUpperCase() + lower.slice(1);
  }).join('') || 'api';
  return /^[A-Za-z_$]/.test(base) && !RESERVED_WORDS.has(base) ? base : `api${base.charAt(0).toUpperCase()}${base.slice(1)}`;
}

export function generationProblems(contract) {
  const problems = [];
  (contract.clientDeps || []).forEach((dep) => {
    if (!SUPPORTED_CLIENT_DEPS.has(dep.from)) problems.push(`unknown clientDep kind ${dep.from}`);
  });
  if (contract.graphql && !graphqlQuery(contract) && !graphqlPersistedHash(contract)) {
    problems.push('GraphQL contract has no query document or persisted hash');
  }
  return problems;
}

export function emitApiConfig(contracts) {
  const firstParty = contracts.find((contract) => contract.origin === 'first-party');
  let base = '';
  if (firstParty?.endpoint) {
    const parsed = new URL(firstParty.endpoint);
    base = parsed.origin;
  }
  const headerLines = contracts.map((contract) => {
    const names = (contract.auth?.headerNames || []).filter((name) => String(name).toLowerCase() !== 'content-type');
    return names.length ? `// - ${contract.id}: ${names.join(', ')}` : `// - ${contract.id}: none`;
  });

  return [
    `const SOURCE_API_BASE = ${singleQuoted(base)};`,
    '',
    'const API_BASES = [',
    "  { match: (hostname) => hostname === 'localhost', base: SOURCE_API_BASE },",
    "  { match: (hostname) => hostname.endsWith('.aem.page'), base: SOURCE_API_BASE },",
    "  { match: (hostname) => hostname.endsWith('.aem.live'), base: SOURCE_API_BASE },",
    "  { match: () => true, base: '' },",
    '];',
    '',
    'export function apiBaseFor(hostname = window.location.hostname) {',
    '  return API_BASES.find((entry) => entry.match(hostname)).base;',
    '}',
    '',
    '// Required auth headers by contract. Fill values in the project repo; never commit secrets.',
    ...headerLines,
    'export function apiHeadersFor(id) {',
    '  return {};',
    '}',
    '',
  ].join('\n');
}

function emitGeneratedHelpers() {
  return `
function cloneTemplate(value) {
  if (Array.isArray(value)) return value.map((entry) => cloneTemplate(entry));
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, cloneTemplate(entry)]),
    );
  }
  return value;
}

function pathParts(path) {
  return String(path || '').replace(/\\[(\\d+)\\]/g, '.$1').split('.').filter(Boolean);
}

function setPath(target, path, value) {
  const parts = pathParts(path);
  if (!parts.length) return target;
  let current = target;
  parts.slice(0, -1).forEach((part, index) => {
    if (!current[part] || typeof current[part] !== 'object') {
      current[part] = /^\\d+$/.test(parts[index + 1]) ? [] : {};
    }
    current = current[part];
  });
  current[parts.at(-1)] = value;
  return target;
}

function valueFor(values, path) {
  return hasValue(values, path) ? values[path] : '';
}

function hasValue(values, path) {
  return Object.prototype.hasOwnProperty.call(values, path);
}

function flattenEntries(value, base = '') {
  if (Array.isArray(value)) {
    return value.flatMap((entry, index) => {
      const path = base ? \`\${base}[\${index}]\` : String(index);
      return flattenEntries(entry, path);
    });
  }
  if (value && typeof value === 'object') {
    return Object.entries(value).flatMap(([key, entry]) => {
      const path = base ? \`\${base}.\${key}\` : key;
      return flattenEntries(entry, path);
    });
  }
  return [[base, value ?? '']];
}

function cookieValue(name) {
  const prefix = \`\${name}=\`;
  const cookie = (document.cookie || '')
    .split(';')
    .map((entry) => entry.trim())
    .find((entry) => entry.startsWith(prefix));
  return cookie ? decodeURIComponent(cookie.slice(prefix.length)) : null;
}

const recaptchaLoadPromises = new Map();

function recaptchaOwner(dep) {
  return dep.from === 'recaptcha-enterprise' ? window.grecaptcha?.enterprise : window.grecaptcha;
}

function recaptchaScriptUrl(dep) {
  const script = dep.from === 'recaptcha-enterprise' ? 'enterprise.js' : 'api.js';
  return \`https://www.google.com/recaptcha/\${script}?render=\${encodeURIComponent(dep.siteKey)}\`;
}

function loadRecaptcha(dep) {
  if (recaptchaOwner(dep)?.execute) return Promise.resolve();
  const key = \`\${dep.from}:\${dep.siteKey}\`;
  if (!recaptchaLoadPromises.has(key)) {
    recaptchaLoadPromises.set(key, new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = recaptchaScriptUrl(dep);
      script.async = true;
      script.onload = resolve;
      script.onerror = () => reject(new Error('reCAPTCHA script failed to load'));
      document.head.appendChild(script);
    }));
  }
  return recaptchaLoadPromises.get(key);
}

async function recaptchaToken(dep) {
  await loadRecaptcha(dep);
  const owner = recaptchaOwner(dep);
  if (!owner?.execute) throw new Error('reCAPTCHA is unavailable');
  await new Promise((resolve) => {
    if (owner.ready) owner.ready(resolve);
    else resolve();
  });
  return owner.execute(dep.siteKey, { action: dep.action });
}

async function applyClientDeps(payload) {
  await Promise.all(CLIENT_DEPS.map(async (dep) => {
    if (dep.from === 'recaptcha' || dep.from === 'recaptcha-enterprise') {
      setPath(payload, dep.path, await recaptchaToken(dep));
    } else if (dep.from === 'cookie') {
      setPath(payload, dep.path, cookieValue(dep.name));
    } else if (dep.from === 'title') {
      setPath(payload, dep.path, document.title);
    } else if (dep.from === 'location') {
      setPath(payload, dep.path, window.location.href);
    }
  }));
  return payload;
}

function firstPartyUrl(values) {
  const parsed = new URL(ENDPOINT);
  const basePath = \`\${parsed.pathname}\${parsed.search}\`;
  const url = new URL(\`\${apiBaseFor()}\${basePath}\`, window.location.href);
  QUERY_KEYS.forEach((key) => {
    url.searchParams.set(key, hasValue(values, key) ? values[key] : '');
  });
  return url.href;
}

function endpointUrl(values) {
  if (ORIGIN === 'first-party') return firstPartyUrl(values);
  const url = new URL(ENDPOINT, window.location.href);
  QUERY_KEYS.forEach((key) => {
    url.searchParams.set(key, hasValue(values, key) ? values[key] : '');
  });
  return url.href;
}

function graphqlPayload(payload) {
  const variables = payload && payload.variables && typeof payload.variables === 'object'
    ? payload.variables
    : GRAPHQL_VARIABLES;
  const body = {
    operationName: GRAPHQL_OPERATION_NAME,
    query: GRAPHQL_QUERY,
    variables,
  };
  if (GRAPHQL_HASH) {
    body.extensions = { persistedQuery: { version: 1, sha256Hash: GRAPHQL_HASH } };
  }
  return body;
}

function multipartBody(values, payload) {
  const body = new FormData();
  if (!MULTIPART_FIELDS.length) {
    flattenEntries(payload).forEach(([key, value]) => {
      body.append(key, value);
    });
    return body;
  }
  MULTIPART_FIELDS.forEach(({ name, path }) => {
    const value = hasValue(values, path) ? values[path] : valueFor(values, name);
    body.append(name, value);
  });
  return body;
}

function encodedBody(payload, values) {
  if (METHOD === 'GET') return undefined;
  if (GRAPHQL) return JSON.stringify(graphqlPayload(payload));
  if (CONTENT_TYPE === 'application/json') return JSON.stringify(payload);
  if (CONTENT_TYPE === 'application/x-www-form-urlencoded') {
    return new URLSearchParams(flattenEntries(payload));
  }
  if (CONTENT_TYPE === 'multipart/form-data') return multipartBody(values, payload);
  return payload === null || payload === undefined ? undefined : String(payload);
}

function requestHeaders() {
  const headers = { ...BASE_HEADERS };
  return { ...headers, ...apiHeadersFor(ID) };
}

async function parseResponse(response) {
  const contentType = response.headers && typeof response.headers.get === 'function'
    ? response.headers.get('content-type') || ''
    : '';
  if (contentType.toLowerCase().includes('json')) {
    return response.json().catch(() => null);
  }
  return response.text().catch(() => '');
}
`;
}

export function emitClientModule(contract) {
  const contentType = String(contract.contentType || '').split(';')[0].trim().toLowerCase();
  const baseHeaders = {};
  if (contentType === 'application/json' || contract.graphql) baseHeaders['content-type'] = 'application/json';
  else if (contentType === 'application/x-www-form-urlencoded') baseHeaders['content-type'] = 'application/x-www-form-urlencoded';
  const accept = acceptHeader(contract);
  if (accept) baseHeaders.accept = accept;

  const constants = (contract.clientDeps || []).filter((dep) => dep.from === 'constant')
    .map(({ path, value }) => ({ path, value }));
  const clientDeps = (contract.clientDeps || []).filter((dep) => dep.from !== 'constant');
  const fields = (contract.fieldMap || []).map(({ path, name }) => ({ path, name }));
  const alias = camelAlias(contract.id);
  const query = graphqlQuery(contract);
  const persistedHash = graphqlPersistedHash(contract);
  const multipart = multipartFields(contract, contentType);

  return [
    generatedMarker(contract.id),
    "import { apiBaseFor, apiHeadersFor } from '../api-config.js';",
    '',
    `const ID = ${jsLiteral(contract.id)};`,
    `const ENDPOINT = ${jsLiteral(contract.endpoint)};`,
    `const METHOD = ${jsLiteral(String(contract.method || 'GET').toUpperCase())};`,
    `const CONTENT_TYPE = ${jsLiteral(contentType)};`,
    `const ORIGIN = ${jsLiteral(contract.origin || 'third-party')};`,
    `const AUTH_SCHEME = ${jsLiteral(contract.auth?.scheme || 'none')};`,
    `const GRAPHQL = ${contract.graphql ? 'true' : 'false'};`,
    `const GRAPHQL_OPERATION_NAME = ${jsLiteral(contract.graphql?.operationName || '')};`,
    `const GRAPHQL_QUERY = ${query ? jsLiteral(query) : 'null'};`,
    `const GRAPHQL_HASH = ${persistedHash ? jsLiteral(persistedHash) : 'null'};`,
    `const GRAPHQL_VARIABLES = ${jsLiteral(contract.graphql?.variables || {})};`,
    `const QUERY_KEYS = ${jsLiteral(queryKeys(contract))};`,
    `const REQUEST_TEMPLATE = ${jsLiteral(requestTemplate(contract))};`,
    `const FIELD_PATHS = ${jsLiteral((contract.fieldMap || []).map((entry) => entry.path))};`,
    `const MULTIPART_FIELDS = ${jsLiteral(multipart)};`,
    `const CONSTANT_DEPS = ${jsLiteral(constants)};`,
    `const CLIENT_DEPS = ${jsLiteral(clientDeps)};`,
    `const BASE_HEADERS = ${jsLiteral(baseHeaders)};`,
    '',
    `export const FIELDS = ${jsLiteral(fields)};`,
    emitGeneratedHelpers(),
    'export function buildPayload(values = {}) {',
    '  const payload = cloneTemplate(REQUEST_TEMPLATE);',
    '  FIELD_PATHS.forEach((path) => {',
    '    setPath(payload, path, valueFor(values, path));',
    '  });',
    '  CONSTANT_DEPS.forEach((dep) => {',
    '    setPath(payload, dep.path, dep.value);',
    '  });',
    '  return payload;',
    '}',
    '',
    'async function apiCall(values = {}, { signal } = {}) {',
    '  try {',
    '    const payload = await applyClientDeps(buildPayload(values));',
    '    const response = await fetch(endpointUrl(values), {',
    '      method: METHOD,',
    '      headers: requestHeaders(),',
    '      body: encodedBody(payload, values),',
    '      signal,',
    "      credentials: AUTH_SCHEME === 'cookie' ? 'include' : 'same-origin',",
    '    });',
    '    const parsed = await parseResponse(response);',
    '    return {',
    '      ok: response.ok,',
    '      status: response.status,',
    '      data: response.ok ? parsed : null,',
    '      error: response.ok ? null : parsed,',
    '    };',
    '  } catch (error) {',
    '    return { ok: false, status: 0, data: null, error: error.message || String(error) };',
    '  }',
    '}',
    '',
    `export { apiCall as ${alias} };`,
    'export default apiCall;',
    '',
  ].join('\n');
}
