#!/usr/bin/env node
// martech-scaffold: contract → scripts/martech.js + hooks (idempotent, conflict-safe, validated), and the generated
// runtime against a stubbed window/document (host gate, ?martech=on / &consent=accept, category gating, boot).
// Run: node plugins/stardust/skills/deploy/scripts/test/martech-scaffold.test.mjs
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SCAFFOLD = join(dirname(fileURLToPath(import.meta.url)), '..', 'martech-scaffold.mjs');
const TMP = mkdtempSync(join(tmpdir(), 'martech-scaffold-'));
const SCRIPTS = `async function loadEager(doc) {
  document.documentElement.lang = 'en';
}

function loadDelayed() {
  // eslint-disable-next-line import/no-cycle
  window.setTimeout(() => import('./delayed.js'), 3000);
}
`;
const CMP = 'https://cmp.example.test/otSDKStub.js';
const LAUNCH = 'https://assets.example.test/launch-1.min.js';
const GTM = 'https://tags.example.test/gtm.js?id=GTM-TEST';
const contract = (over = {}) => ({
  productionHosts: ['www.example.test'],
  consent: {
    cmp: { vendor: 'OneTrust', src: CMP, attrs: { 'data-domain-script': 'test-id' }, groups: 'OnetrustActiveGroups', event: 'OneTrustGroupsUpdated', enabled: true },
    model: 'per-tag',
  },
  routes: [
    { id: 'adobe-launch', src: LAUNCH, boot: null, category: null, enabled: true },
    { id: 'gtm', src: GTM, boot: 'gtm', category: 'C0004', enabled: true },
    { id: 'off', src: 'https://off.example.test/x.js', boot: null, category: null, enabled: false },
  ],
  ...over,
});

let seq = 0;
function site({ data = contract(), delayed = '// add delayed functionality here\n', scripts = SCRIPTS } = {}) {
  seq += 1;
  const root = join(TMP, `site-${seq}`);
  mkdirSync(join(root, 'scripts'), { recursive: true });
  mkdirSync(join(root, 'stardust'));
  writeFileSync(join(root, 'scripts/scripts.js'), scripts);
  if (delayed !== null) writeFileSync(join(root, 'scripts/delayed.js'), delayed);
  writeFileSync(join(root, 'stardust/martech-contract.json'), JSON.stringify(data));
  return root;
}
const run = (root, ...args) => spawnSync(process.execPath, [SCAFFOLD, '--root', root, ...args], { encoding: 'utf8' });
const file = (root, p) => readFileSync(join(root, p), 'utf8');

let failed = 0;
const check = async (name, fn) => { try { await fn(); console.log(`✓ ${name}`); } catch (e) { failed += 1; console.log(`✗ ${name}\n  ${e.message.split('\n').join('\n  ')}`); } };

await check('writes martech.js with enabled routes only, hooks loadEager + delayed.js; re-run is unchanged', () => {
  const root = site();
  const r = run(root);
  assert.equal(r.status, 0, r.stderr);
  const js = file(root, 'scripts/martech.js');
  assert.ok(js.includes(LAUNCH) && js.includes(GTM) && !js.includes('off.example.test'));
  assert.ok(!js.includes('"'), 'config is emitted with single quotes');
  assert.match(file(root, 'scripts/scripts.js'), /function loadEager\(doc\) \{\n {2}import\('\.\/martech\.js'\)\.then\(\(m\) => m\.loadConsent\(\)\);/);
  assert.match(file(root, 'scripts/delayed.js'), /m\.loadTags\(\)/);
  const again = run(root);
  assert.equal(again.status, 0);
  assert.match(again.stdout, /unchanged/);
});

await check('no delayed.js: loadTags goes into loadDelayed(); missing loadEager is a usage error', () => {
  const root = site({ delayed: null });
  assert.equal(run(root).status, 0);
  assert.match(file(root, 'scripts/scripts.js'), /function loadDelayed\(\) \{\n {2}import\('\.\/martech\.js'\)\.then\(\(m\) => m\.loadTags\(\)\);/);
  const bare = run(site({ scripts: 'export {};\n' }));
  assert.equal(bare.status, 1); assert.match(bare.stderr, /no loadEager\(\)/);
});

await check('--dry-run writes nothing; a foreign martech.js is a conflict unless --force', () => {
  const root = site();
  assert.match(run(root, '--dry-run').stdout, /would write scripts\/martech\.js/);
  assert.equal(file(root, 'scripts/scripts.js'), SCRIPTS);
  writeFileSync(join(root, 'scripts/martech.js'), 'export default 1;\n');
  const conflict = run(root);
  assert.equal(conflict.status, 1); assert.match(conflict.stderr, /not written by this scaffold/);
  assert.equal(run(root, '--force').status, 0);
  assert.match(file(root, 'scripts/martech.js'), /^\/\/ Generated by stardust/);
});

await check('invalid contract: enabled CMP without its id, or a category the CMP cannot gate', () => {
  const noId = contract();
  noId.consent.cmp.attrs['data-domain-script'] = null;
  const a = run(site({ data: noId }));
  assert.equal(a.status, 1); assert.match(a.stderr, /data-domain-script/);
  const noGroups = contract();
  Object.assign(noGroups.consent.cmp, { vendor: 'Cookiebot', groups: null, event: null });
  const b = run(site({ data: noGroups }));
  assert.equal(b.status, 1); assert.match(b.stderr, /route `gtm` has a category/);
});

const SITE = site();
run(SITE);
async function boot({ host = 'main--site--org.aem.page', search = '', groups, root = SITE } = {}) {
  const added = [];
  const listeners = {};
  globalThis.window = {
    location: { host, search },
    OnetrustActiveGroups: groups,
    addEventListener: (type, fn) => { listeners[type] = fn; },
    removeEventListener: (type) => { delete listeners[type]; },
  };
  globalThis.document = {
    createElement: () => ({ attrs: {}, setAttribute(k, v) { this.attrs[k] = v; } }),
    head: { append: (s) => added.push(s) },
  };
  seq += 1;
  const m = await import(`${pathToFileURL(join(root, 'scripts/martech.js')).href}?${seq}`);
  m.loadConsent();
  m.loadTags();
  return { win: globalThis.window, srcs: () => added.map((s) => s.src), added, fire: () => listeners.OneTrustGroupsUpdated?.() };
}

await check('runtime: off the production hosts nothing loads without ?martech=on', async () => {
  assert.deepEqual((await boot()).srcs(), []);
});

await check('runtime: ?martech=on&consent=accept loads the CMP and every enabled route; gtm gets its bootstrap', async () => {
  const b = await boot({ search: '?martech=on&consent=accept' });
  assert.deepEqual(b.srcs(), [CMP, LAUNCH, GTM]);
  assert.equal(b.added[0].attrs['data-domain-script'], 'test-id');
  assert.equal(b.win.dataLayer[0].event, 'gtm.js');
});

await check('runtime: production — ungated route loads at once, the C0004 route waits for the CMP to grant it', async () => {
  const b = await boot({ host: 'www.example.test', groups: ',C0001,' });
  assert.deepEqual(b.srcs(), [CMP, LAUNCH]);
  b.fire();
  assert.deepEqual(b.srcs(), [CMP, LAUNCH]);
  b.win.OnetrustActiveGroups = ',C0001,C0004,';
  b.fire();
  assert.deepEqual(b.srcs(), [CMP, LAUNCH, GTM]);
});

await check('runtime: consent=accept is ignored on a production host', async () => {
  const b = await boot({ host: 'www.example.test', search: '?consent=accept', groups: ',C0001,' });
  assert.deepEqual(b.srcs(), [CMP, LAUNCH]);
});

await check('runtime: a gtag route defines gtag and configures the id from its src', async () => {
  const GTAG = 'https://www.googletagmanager.com/gtag/js?id=G-TEST';
  const root = site({ data: contract({ routes: [{ id: 'gtag', src: GTAG, boot: 'gtag', category: null, enabled: true }] }) });
  assert.equal(run(root).status, 0);
  const b = await boot({ root, search: '?martech=on' });
  assert.deepEqual(b.srcs(), [CMP, GTAG]);
  assert.deepEqual(b.win.dataLayer.map((a) => [...a]), [['js', b.win.dataLayer[0][1]], ['config', 'G-TEST']]);
});

const AM = (over = {}) => ({
  plugin: { name: 'aem-martech', path: 'plugins/martech', repo: 'https://example.test/aem-martech.git' },
  config: { orgId: 'TEST@AdobeOrg', datastreamId: 'ds-test', alloyInstanceName: 'alloy', edgeDomain: null, defaultConsent: 'in', launchUrls: [LAUNCH] },
  category: null,
  enabled: true,
  ...over,
});
const STUB = `const log = (globalThis.martechCalls ||= []);
export const initMartech = async (w, o) => { log.push(['init', w, o]); };
export const martechEager = async () => { log.push(['eager']); };
export const martechLazy = async () => { log.push(['lazy']); };
export const martechDelayed = async () => { log.push(['delayed']); };
export const updateUserConsent = async (c) => { log.push(['consent', c]); };
`;
const amSite = (am, routes = [{ id: 'adobe-launch', src: LAUNCH, boot: null, category: null, enabled: false }]) => {
  const root = site({ data: contract({ routes, aemMartech: am }) });
  mkdirSync(join(root, 'plugins/martech/src'), { recursive: true });
  writeFileSync(join(root, 'plugins/martech/src/index.js'), STUB);
  return root;
};

await check('aemMartech: missing plugin, empty ids, the Launch route still enabled, or pending with no category are errors', () => {
  const noPlugin = run(site({ data: contract({ aemMartech: AM() }) }));
  assert.equal(noPlugin.status, 1); assert.match(noPlugin.stderr, /git subtree add --squash --prefix plugins\/martech/);
  const noDs = run(amSite(AM({ config: { ...AM().config, datastreamId: null } })));
  assert.equal(noDs.status, 1); assert.match(noDs.stderr, /config\.datastreamId/);
  const twice = run(amSite(AM(), [{ id: 'adobe-launch', src: LAUNCH, boot: null, category: null, enabled: true }]));
  assert.equal(twice.status, 1); assert.match(twice.stderr, /route `adobe-launch` is enabled and also in aemMartech\.config\.launchUrls/);
  const pending = run(amSite(AM({ config: { ...AM().config, defaultConsent: 'pending' } })));
  assert.equal(pending.status, 1); assert.match(pending.stderr, /nothing would ever be sent/);
});

await check('aemMartech disabled: martech.js is byte-identical to a contract without it', () => {
  const a = site(); const b = site({ data: contract({ aemMartech: AM({ enabled: false }) }) });
  run(a); run(b);
  assert.equal(file(a, 'scripts/martech.js'), file(b, 'scripts/martech.js'));
});

await check('runtime: aemMartech inits the Web SDK with the source consent, then lazy + delayed (which loads Launch)', async () => {
  const root = amSite(AM());
  const r = run(root);
  assert.equal(r.status, 0, r.stderr); assert.match(r.stdout, /Web SDK via aem-martech/);
  globalThis.martechCalls = [];
  const b = await boot({ root, search: '?martech=on' });
  await new Promise((done) => { setTimeout(done, 20); });
  assert.deepEqual(b.srcs(), [CMP]);
  const [init, ...rest] = globalThis.martechCalls;
  assert.deepEqual(init, ['init', { orgId: 'TEST@AdobeOrg', datastreamId: 'ds-test', defaultConsent: 'in' }, { alloyInstanceName: 'alloy', launchUrls: [LAUNCH], personalization: false }]);
  assert.deepEqual(rest.map((c) => c[0]), ['eager', 'lazy', 'delayed']);
});

await check('runtime: an aemMartech category sets collect only once the CMP grants it', async () => {
  const root = amSite(AM({ category: 'C0002', config: { ...AM().config, defaultConsent: 'pending' } }));
  assert.equal(run(root).status, 0);
  globalThis.martechCalls = [];
  const b = await boot({ root, host: 'www.example.test', groups: ',C0001,' });
  await new Promise((done) => { setTimeout(done, 20); });
  assert.ok(!globalThis.martechCalls.some((c) => c[0] === 'consent'));
  b.win.OnetrustActiveGroups = ',C0001,C0002,';
  b.fire();
  assert.deepEqual(globalThis.martechCalls.find((c) => c[0] === 'consent'), ['consent', { collect: true }]);
});

await check('--help prints the usage header', () => {
  const r = spawnSync(process.execPath, [SCAFFOLD, '--help'], { encoding: 'utf8' });
  assert.equal(r.status, 0); assert.match(r.stdout, /--dry-run/);
});

rmSync(TMP, { recursive: true, force: true });
console.log(failed ? `\nmartech-scaffold: ${failed} check(s) failed` : '\nmartech-scaffold: all checks passed');
process.exit(failed ? 1 : 0);
